### ISSUE TITLE
Unix socket tests failing on RHEL5, Python 2.7

### ISSUE THREAD

**Issue by hoffman** [joshmarshall/jsonrpclib#12]
```
$ uname -srv
Linux 2.6.18-238.1.1.el5 #1 SMP Tue Jan 4 13:32:19 EST 2011

$ python -V
Python 2.7

$ python tests.py
===============================================================
  NOTE: There may be threading exceptions after tests finish.  
===============================================================
....................EEEEEEEE
======================================================================
ERROR: test_connect (__main__.UnixSocketInternalTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 279, in test_connect
    result = client.ping()
  File "/net/noble/vol2/home/mmh1/sandbox/jsonrpclib/jsonrpclib/jsonrpc.py", line 276, in __call__
    return self.__send(self.__name, kwargs)
  File "/net/noble/vol2/home/mmh1/sandbox/jsonrpclib/jsonrpclib/jsonrpc.py", line 224, in _request
    response = self._run_request(request)
  File "/net/noble/vol2/home/mmh1/sandbox/jsonrpclib/jsonrpclib/jsonrpc.py", line 242, in _run_request
    verbose=self.__verbose
  File "/net/gs/vol3/software/modules-sw/python/2.7/Linux/RHEL5/x86_64/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/net/gs/vol3/software/modules-sw/python/2.7/Linux/RHEL5/x86_64/lib/python2.7/xmlrpclib.py", line 1303, in single_request
    self.close()
  File "/net/gs/vol3/software/modules-sw/python/2.7/Linux/RHEL5/x86_64/lib/python2.7/xmlrpclib.py", line 1378, in close
    if self._connection[1]:
TypeError: 'NoneType' object is not subscriptable

======================================================================
ERROR: test_multicall_failure (__main__.UnixSocketInternalTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 341, in test_multicall_failure
    result = multicall()
  File "/net/noble/vol2/home/mmh1/sandbox/jsonrpclib/jsonrpclib/jsonrpc.py", line 362, in _request
    responses = self._server._run_request(request_body)
  File "/net/noble/vol2/home/mmh1/sandbox/jsonrpclib/jsonrpclib/jsonrpc.py", line 242, in _run_request
    verbose=self.__verbose
  File "/net/gs/vol3/software/modules-sw/python/2.7/Linux/RHEL5/x86_64/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/net/gs/vol3/software/modules-sw/python/2.7/Linux/RHEL5/x86_64/lib/python2.7/xmlrpclib.py", line 1303, in single_request
    self.close()
  File "/net/gs/vol3/software/modules-sw/python/2.7/Linux/RHEL5/x86_64/lib/python2.7/xmlrpclib.py", line 1378, in close
    if self._connection[1]:
TypeError: 'NoneType' object is not subscriptable

======================================================================
ERROR: test_multicall_success (__main__.UnixSocketInternalTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 333, in test_multicall_success
    result = multicall()
  File "/net/noble/vol2/home/mmh1/sandbox/jsonrpclib/jsonrpclib/jsonrpc.py", line 362, in _request
    responses = self._server._run_request(request_body)
  File "/net/noble/vol2/home/mmh1/sandbox/jsonrpclib/jsonrpclib/jsonrpc.py", line 242, in _run_request
    verbose=self.__verbose
  File "/net/gs/vol3/software/modules-sw/python/2.7/Linux/RHEL5/x86_64/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/net/gs/vol3/software/modules-sw/python/2.7/Linux/RHEL5/x86_64/lib/python2.7/xmlrpclib.py", line 1303, in single_request
    self.close()
  File "/net/gs/vol3/software/modules-sw/python/2.7/Linux/RHEL5/x86_64/lib/python2.7/xmlrpclib.py", line 1378, in close
    if self._connection[1]:
TypeError: 'NoneType' object is not subscriptable

======================================================================
ERROR: test_single_args (__main__.UnixSocketInternalTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 284, in test_single_args
    result = client.add(5, 10)
  File "/net/noble/vol2/home/mmh1/sandbox/jsonrpclib/jsonrpclib/jsonrpc.py", line 274, in __call__
    return self.__send(self.__name, args)
  File "/net/noble/vol2/home/mmh1/sandbox/jsonrpclib/jsonrpclib/jsonrpc.py", line 224, in _request
    response = self._run_request(request)
  File "/net/noble/vol2/home/mmh1/sandbox/jsonrpclib/jsonrpclib/jsonrpc.py", line 242, in _run_request
    verbose=self.__verbose
  File "/net/gs/vol3/software/modules-sw/python/2.7/Linux/RHEL5/x86_64/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/net/gs/vol3/software/modules-sw/python/2.7/Linux/RHEL5/x86_64/lib/python2.7/xmlrpclib.py", line 1303, in single_request
    self.close()
  File "/net/gs/vol3/software/modules-sw/python/2.7/Linux/RHEL5/x86_64/lib/python2.7/xmlrpclib.py", line 1378, in close
    if self._connection[1]:
TypeError: 'NoneType' object is not subscriptable

======================================================================
ERROR: test_single_kwargs (__main__.UnixSocketInternalTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 289, in test_single_kwargs
    result = client.add(x=5, y=10)
  File "/net/noble/vol2/home/mmh1/sandbox/jsonrpclib/jsonrpclib/jsonrpc.py", line 276, in __call__
    return self.__send(self.__name, kwargs)
  File "/net/noble/vol2/home/mmh1/sandbox/jsonrpclib/jsonrpclib/jsonrpc.py", line 224, in _request
    response = self._run_request(request)
  File "/net/noble/vol2/home/mmh1/sandbox/jsonrpclib/jsonrpclib/jsonrpc.py", line 242, in _run_request
    verbose=self.__verbose
  File "/net/gs/vol3/software/modules-sw/python/2.7/Linux/RHEL5/x86_64/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/net/gs/vol3/software/modules-sw/python/2.7/Linux/RHEL5/x86_64/lib/python2.7/xmlrpclib.py", line 1303, in single_request
    self.close()
  File "/net/gs/vol3/software/modules-sw/python/2.7/Linux/RHEL5/x86_64/lib/python2.7/xmlrpclib.py", line 1378, in close
    if self._connection[1]:
TypeError: 'NoneType' object is not subscriptable

======================================================================
ERROR: test_single_kwargs_and_args (__main__.UnixSocketInternalTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 294, in test_single_kwargs_and_args
    self.assertRaises(ProtocolError, client.add, (5,), {'y':10})
  File "/net/gs/vol3/software/modules-sw/python/2.7/Linux/RHEL5/x86_64/lib/python2.7/unittest/case.py", line 456, in assertRaises
    callableObj(*args, **kwargs)
  File "/net/noble/vol2/home/mmh1/sandbox/jsonrpclib/jsonrpclib/jsonrpc.py", line 274, in __call__
    return self.__send(self.__name, args)
  File "/net/noble/vol2/home/mmh1/sandbox/jsonrpclib/jsonrpclib/jsonrpc.py", line 224, in _request
    response = self._run_request(request)
  File "/net/noble/vol2/home/mmh1/sandbox/jsonrpclib/jsonrpclib/jsonrpc.py", line 242, in _run_request
    verbose=self.__verbose
  File "/net/gs/vol3/software/modules-sw/python/2.7/Linux/RHEL5/x86_64/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/net/gs/vol3/software/modules-sw/python/2.7/Linux/RHEL5/x86_64/lib/python2.7/xmlrpclib.py", line 1303, in single_request
    self.close()
  File "/net/gs/vol3/software/modules-sw/python/2.7/Linux/RHEL5/x86_64/lib/python2.7/xmlrpclib.py", line 1378, in close
    if self._connection[1]:
TypeError: 'NoneType' object is not subscriptable

======================================================================
ERROR: test_single_namespace (__main__.UnixSocketInternalTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 303, in test_single_namespace
    response = client.namespace.sum(1,2,4)
  File "/net/noble/vol2/home/mmh1/sandbox/jsonrpclib/jsonrpclib/jsonrpc.py", line 274, in __call__
    return self.__send(self.__name, args)
  File "/net/noble/vol2/home/mmh1/sandbox/jsonrpclib/jsonrpclib/jsonrpc.py", line 224, in _request
    response = self._run_request(request)
  File "/net/noble/vol2/home/mmh1/sandbox/jsonrpclib/jsonrpclib/jsonrpc.py", line 242, in _run_request
    verbose=self.__verbose
  File "/net/gs/vol3/software/modules-sw/python/2.7/Linux/RHEL5/x86_64/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/net/gs/vol3/software/modules-sw/python/2.7/Linux/RHEL5/x86_64/lib/python2.7/xmlrpclib.py", line 1303, in single_request
    self.close()
  File "/net/gs/vol3/software/modules-sw/python/2.7/Linux/RHEL5/x86_64/lib/python2.7/xmlrpclib.py", line 1378, in close
    if self._connection[1]:
TypeError: 'NoneType' object is not subscriptable

======================================================================
ERROR: test_single_notify (__main__.UnixSocketInternalTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 298, in test_single_notify
    result = client._notify.add(5, 10)
  File "/net/noble/vol2/home/mmh1/sandbox/jsonrpclib/jsonrpclib/jsonrpc.py", line 274, in __call__
    return self.__send(self.__name, args)
  File "/net/noble/vol2/home/mmh1/sandbox/jsonrpclib/jsonrpclib/jsonrpc.py", line 231, in _request_notify
    response = self._run_request(request, notify=True)
  File "/net/noble/vol2/home/mmh1/sandbox/jsonrpclib/jsonrpclib/jsonrpc.py", line 242, in _run_request
    verbose=self.__verbose
  File "/net/gs/vol3/software/modules-sw/python/2.7/Linux/RHEL5/x86_64/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/net/gs/vol3/software/modules-sw/python/2.7/Linux/RHEL5/x86_64/lib/python2.7/xmlrpclib.py", line 1303, in single_request
    self.close()
  File "/net/gs/vol3/software/modules-sw/python/2.7/Linux/RHEL5/x86_64/lib/python2.7/xmlrpclib.py", line 1378, in close
    if self._connection[1]:
TypeError: 'NoneType' object is not subscriptable

----------------------------------------------------------------------
Ran 28 tests in 0.124s

FAILED (errors=8)
```

**Comment by joshmarshall** [comment]
Closing this issue, as Unix socket tests should succeed in Python 3.5+.
